### ISSUE TITLE
Concurrent Read Write on tf Variable?

### ISSUE THREAD

**Issue by mavenlin** [SimonRamstedt/ddpg#3]
I've seen several possible concurrent reads and writes in your code.
- `train_p` and `train_q` has no control dependency on each other, `train_q` updates `q_theta` which is also used in `train_p`. It is possible they may conflict with each other. 
- `train_p` updates `p_theta_target`, which is used in `train_q`, and the order is also undefined.

**Comment by rmst** [comment]
Hey, thanks for the feedback! I just added separate functions for p and q training and an option to run synchronously (`--async False`). Updating concurrently is fast and I don't think it hurts performance since the changes at every step are only very small. I'm currently testing whether there is a difference in performance.

**Comment by rmst** [comment]
ok it doesn't look like concurrent updating is hurting performance
